language: node_js
node_js:
- '6.1'
env:
  global:
    secure: skIkXniSf1qWCMEvJ3r1PU7zwMnWSQ6q37Y1jihYGd16h1zaNdmLHo7TiNS7f3s8EwHO8/1uWHatEVScLvd7pn4HB+hLyE1T4lR3idagTwyWhDuJFJGGyi+WO+vCwdHe2p7iDasOOPhFQ/L0J96ZwRIQK1rey+NXoRhEWJ0WqqfPyufrAi8/rSjWHWibW8ffFPXHJexc9fO76QYHDyD1PBy/EQRpdhqjtQ+mJpdi+m/a4MQcwh1S+ozbqfF3/XxwpvXXzUrlmFfSCfkmkie8poTSEZcgBksUuJzOwh+Pu4xDFTdIYDMCv3KT41c7v/FNu9JG03SksCqeZnVq5wv8Wq6npxIp90pCS6a90uT1IlL4jG9T8QxcII033H5AdDm2wlzu6jZcq6eA764eelZJ2zv1AMfMwSMv+jCdwsjZW180rh5bnnGQ1umGIRWkB448XOvissa01Ayrma9aiEVsSUJnMCc+/TElr1V0G5Bh9fsgW/sgKCE+6PAvrFKbv+ZhVcbL14/fL2vQyXmgKD0ggayBsenvGnsHkF1OuVi6URLtoocLdKVZQZU5FiNSJ12n/nrmFdaFw79Zp1TIU2hO/ZVgh87SBXuvxZq54TdrmAVwvgcnyMvFQw4Bn6obBkqYhh3Z9ZPmPFpwM2NhVjYwcf9UdOO+T9DoL/A4clm9LJ4=
